build image:
  image: docker
  services: 
   - docker:dind
   script:
     - docker login -u $CI_REGISTRY_USER $CI_REGISTRY
     - docker build -t $CI_REGISTRY_IMAGE .
     - docker push $CI_REGISTRY_IMAGE 