image: docker:20.10.22
services: 
  - docker:20.10.22-dind

stages:
 - release 
 - deploy

variables:
  VERSION_1_0: 1.0
  LATEST_VERSION: 1.0
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

release-image-v-1-0:
  stage: release
  script:    
    - docker build -t $CONTAINER_RELEASE_IMAGE:$VERSION_1_0 .
    - docker push $CONTAINER_RELEASE_IMAGE:$VERSION_1_0 

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE:$LATEST_VERSION
    - docker tag $CONTAINER_RELEASE_IMAGE:$LATEST_VERSION $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
  only: 
    - main
  environment: 
    name: production
    url: $CONTAINER_LATEST_IMAGE