image: docker:20.10.22
services: 
  - docker:20.10.22-dind

stages:
 - staging
 - deploy

variables:
  CONTAINER_PRODUCTION_IMAGE: $CI_REGISTRY_IMAGE/production:1.0
  CONTAINER_STAGING_IMAGE: $CI_REGISTRY_IMAGE/staging:1.0

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

staging:
  stage: staging
  script:
    - echo -e "DOMAIN_NAME=$DOMAIN_NAME_CI\nENVIRONMENT_NAME=$ENVIRONMENT_STAGING_CI\nALIAS_NAME=$ALIAS_CI\n" > .env    
    - docker build -t  $CONTAINER_STAGING_IMAGE .
    - docker push $CONTAINER_STAGING_IMAGE
  only: 
    - main
  environment: 
    name: staging
    url: $CONTAINER_STAGING_IMAGE

deploy:
  stage: deploy
  script:
    - echo -e "DOMAIN_NAME=$DOMAIN_NAME_CI\nENVIRONMENT_NAME=$ENVIRONMENT_PRODUCTION_CI\nALIAS_NAME=$ALIAS_CI\n" > .env    
    - docker build -t  $CONTAINER_PRODUCTION_IMAGE .
    - docker push $CONTAINER_PRODUCTION_IMAGE
  only: 
    - main
  environment: 
    name: production
    url: $CONTAINER_PRODUCTION_IMAGE