image: docker:20.10.22
services: 
  - docker:20.10.22-dind

stages:
 - release 
 - deploy

variables: 
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/test:1.0
  CONTAINER_PRODUCTION_IMAGE: $CI_REGISTRY_IMAGE:1.0

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

release-image:
  stage: release
  script:    
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

deploy:
  stage: deploy
  script:
    - docker build -t $CONTAINER_PRODUCTION_IMAGE .
    - docker push $CONTAINER_PRODUCTION_IMAGE
  only: 
    - main
  environment: 
    name: production
    url: $CONTAINER_PRODUCTION_IMAGE:1.0