image: docker:20.10.22
services: 
  - docker:20.10.22-dind

stages:
 - release 
 - deploy

variables: 
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:1.0

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 

release-image:
  stage: release
  script:    
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

deploy:
  stage: deploy
  script:    
    - ./deploy.sh
  only: 
    main
  environment: production